import = ["~/.config/alacritty/plugins/gruvbox-dark.toml"]

[shell]
program = "/bin/bash"
args = ["-l", "-c", "zellij delete-all-sessions && zellij attach || zellij --session å½±"]

[window]
opacity = 1
padding = { x = 25, y = 25 }
dynamic_padding = true
decorations = "None"

[font]
normal = { family = "BitstromWera Nerd Font" }
bold = { family = "BitstromWera Nerd Font", style = "Bold" }
size = 15.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 400
blink_timeout = 0

[terminal]
osc52 = "CopyPaste"

[scrolling]
history = 50000
